[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = ["/frontend/**"]

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 5
